version: '2'

services:
    # db:
    #     image: mysql
    #     ports:
    #         - 3303:3306
    #     volumes:
    #         - "./.data/db:/var/lib/mysql:cached"
    #     environment:
    #         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    #         MYSQL_DATABASE: ${MYSQL_DATABASE}
    #         MYSQL_USER: ${MYSQL_USER}
    #         MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # php:
    #     build:
    #         context: php7-fpm
    #         args:
    #             TIMEZONE: ${TIMEZONE}
    #             HOST_USER_ID: ${HOST_USER_ID}
    #             HOST_GROUP_ID: ${HOST_GROUP_ID}
    #     volumes:
    #         - ${SYMFONY_APP_PATH}:/var/www/symfony:cached
    nginx:
        build:
            context: nginx
            args:
                HOST_USER_ID: ${HOST_USER_ID}
                HOST_GROUP_ID: ${HOST_GROUP_ID}
        ports:
            - 8080:80
        # volumes_from:
        #     - php
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached
